export const graphicItems = [
  {
    id: "gd-01",
    title: "Logo Mark — Concept",
    category: "Logo Design",
    thumb: "/work/graphic-design/thumbs/logo-01.jpg",
    full: "/work/graphic-design/full/logo-01.jpg",
    tags: ["Identity"],
  },
  {
    id: "gd-02",
    title: "Brand Mockup Set",
    category: "Mockups",
    thumb: "/work/graphic-design/thumbs/mockup-01.jpg",
    full: "/work/graphic-design/full/mockup-01.jpg",
    tags: ["Branding"],
  },
  {
    id: "gd-03",
    title: "Poster Layout",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-01.jpg",
    full: "/work/graphic-design/full/poster-01.jpg",
    tags: ["Layout"],
  },
  {
  id: "gd-04",
  title: "Event Poster — Cultural Showcase",
  category: "Posters",
  thumb: "/work/graphic-design/thumbs/poster-02.jpg",
  full: "/work/graphic-design/full/poster-02.jpg",
  tags: ["Poster", "Typography", "Layout"],
  description: "Structured grid-based poster design with bold hierarchy.",
},
{
    id: "gd-05",
    title: "Logo Mark — Concept",
    category: "Logo Design",
    thumb: "/work/graphic-design/thumbs/logo-03.jpg",
    full: "/work/graphic-design/full/logo-03.jpg",
    tags: ["Identity"],
  },
  {
  id: "gd-06",
  title: "Event Poster — Church Service",
  category: "Posters",
  thumb: "/work/graphic-design/thumbs/poster-03.jpg",
  full: "/work/graphic-design/full/poster-03.jpg",
  tags: ["Poster", "Typography", "Layout"],
  description: "Structured grid-based poster design with bold hierarchy.",
},
  {
  id: "gd-07",
  title: "Event Poster — Election Campaign",
  category: "Posters",
  thumb: "/work/graphic-design/thumbs/poster-04.jpg",
  full: "/work/graphic-design/full/poster-04.jpg",
  tags: ["Poster", "Typography", "Layout"],
  description: "Structured grid-based poster design with bold hierarchy.",
},
{
    id: "gd-08",
    title: "Product Poster",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-05.jpg",
    full: "/work/graphic-design/full/poster-05.jpg",
    tags: ["Layout"],
  },
  {
    id: "gd-09",
    title: "Product Poster",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-06.jpg",
    full: "/work/graphic-design/full/poster-06.jpg",
    tags: ["Layout"],
  },
  {
    id: "gd-010",
    title: "Product Poster",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-07.jpg",
    full: "/work/graphic-design/full/poster-07.jpg",
    tags: ["Layout"],
  },
    {
    id: "gd-11",
    title: "Product Poster",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-08.jpg",
    full: "/work/graphic-design/full/poster-08.jpg",
    tags: ["Layout"],
  },
   {
    id: "gd-12",
    title: "Product Poster",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-09.jpg",
    full: "/work/graphic-design/full/poster-09.jpg",
    tags: ["Layout"],
  },
   {
    id: "gd-13",
    title: "Product Poster",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-10.jpg",
    full: "/work/graphic-design/full/poster-10.jpg",
    tags: ["Layout"],
  },
  {
    id: "gd-14",
    title: "Table Tent Design",
    category: "Posters",
    thumb: "/work/graphic-design/thumbs/poster-11.jpg",
    full: "/work/graphic-design/full/poster-11.jpg",
    tags: ["Layout"],
  },
  {
  id: "gd-15",
  title: "Event Poster — Appointees Display",
  category: "Posters",
  thumb: "/work/graphic-design/thumbs/poster-12.jpg",
  full: "/work/graphic-design/full/poster-12.jpg",
  tags: ["Poster", "Typography", "Layout"],
  description: "Structured grid-based poster design with bold hierarchy.",
},
];